function mintsData = licorRead(fileName,timeSpan)
%IMPORTFILE Import data from a text file
%  MINTS001E0610C2E7LICOR20201212 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  MINTS001E0610C2E7LICOR20201212 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MINTS001e0610c2e7LICOR20201212 = importfile("/media/teamlary/teamlary1/gitHubRepos/carMintsML/firmware/dataProcessing/MINTS_001e0610c2e7_LICOR_2020_12_12.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Feb-2021 16:37:23

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [2, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "cellTemp", "cellPressure", "CO2", "CO2_abs", "ivolt", "H2O", "H2O_abs", "H2O_dewpoint", "CO2_raw", "CO2_ref", "H2O_raw", "H2O_ref", "flowrate"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "flowrate", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "flowrate", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

% Import the data
    % Import the data
    mintsData = readtable(fileName, opts);
 
    mintsData = removevars( mintsData,...    
                   "flowrate"       ...
               );
           
    mintsData.dateTime.TimeZone = "utc";
    mintsData           = rmmissing(retime(table2timetable(mintsData),'regular',@nanmean,'TimeStep',timeSpan));


end